-- THIS FILE WAS AUTOMATICALLY GENERATED BY TileZed
local overlayMap = {}
overlayMap.VERSION = 1
overlayMap["CH_Tiles_01_7"] = {{ name = "other", tiles = {"CH_Tiles_01_24", "CH_Tiles_01_23"} }}
overlayMap["CH_Tiles_01_16"] = {{ name = "other", tiles = {"CH_Tiles_01_17", "CH_Tiles_01_18"} }}

if not TILEZED then
	getContainerOverlays():addOverlays(overlayMap)
end

return overlayMap
